version: '2'

####################################################################
## Local configuration for Prometheus and a few example services  ##
####################################################################

services:

  #####################
  ## Sample Services ##
  #####################

  random-number-generator:
    image : dgoldstein1/random-number-generator
    ports:
      - 7000:8080

  random-wikipedia:
    image : dgoldstein1/random-wikipedia
    ports:
      - 7001:8080
  
  ###########################
  ## Databases and Storage ##
  ###########################
      
  prom:
    image : prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml