global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: random-number-generator
    static_configs:
      - targets:
        - random-number-generator:8080

  - job_name: random-wikipedia
    static_configs:
      - targets:
        - random-wikipedia:8080